//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleTarefa
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TAREFA
    {
        public int id { get; set; }
        public string descricao { get; set; }
        public Nullable<System.DateTime> dataAtividade { get; set; }
        public Nullable<System.DateTime> dataEntrega { get; set; }
        public Nullable<System.DateTime> dataLimiteEntrega { get; set; }
        public string diagnostico { get; set; }
    }
}
